### ISSUE TITLE
(Suggestion) FastLZ support

### ISSUE THREAD

**Issue by 7k5x** [yuk7/wsldl#109]
I know you've probably never heard of this, but FastLZ is another compression method and is licensed under MIT, so I think an addition could be good?

**Comment by yuk7** [comment]
I think license is okay.
but do you think anyone will use it?
I think the size of the executable file will increase...

**Comment by 7k5x** [comment]
> but do you think anyone will use it?
> I think the size of the executable file will increase...
Oh😅 didn't think of that... I use xz and 7z a lot so I thought it would be nice, but I forgot the `exe` size will increase when implementing it..

**Comment by yuk7** [comment]
and, It seems that it is not possible to expand 7z or xz with FastLZ...

**Comment by 7k5x** [comment]
Oh...I'm so stupid｡ﾟ(｡ﾉωヽ｡)ﾟ｡
