### ISSUE TITLE
Is there a rootfs for ubuntu?

### ISSUE THREAD

**Issue by kingdevnl** [yuk7/wsldl#15]
Is there a rootfs for ubuntu?

**Comment by yuk7** [comment]
I don't provide ubuntu rootfs.tar.gz.
Please download from official site and convert it...

**Comment by kingdevnl** [comment]
What do you mean with convert it?,

**Comment by yuk7** [comment]
Please download *-server-cloudimg-amd64-root.tar.gz  
https://cloud-images.ubuntu.com

You don't need convert it. Sorry.

**Comment by yuk7** [comment]
Please run this command in Ubuntu 's shell in order to be able to connect to the network.
`echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." | sudo tee /etc/resolv.conf`
