### ISSUE TITLE
Fedora 28 segfault

### ISSUE THREAD

**Issue by ranebull** [yuk7/wsldl#19]
Hello! 
When I run Fedora and try use command "yum update" then I get error "Segmentation fault (core dumped)"

**Comment by yuk7** [comment]
I think it is a matter of WSL.
I recommend you to ask questions with WSL issue tracker:
https://github.com/Microsoft/WSL

**Comment by ranebull** [comment]
> I think that is a matter of WSL.
> I recommend you to ask questions with WSL issue tracker:
> https://github.com/Microsoft/WSL

Ok, thx
