### ISSUE TITLE
Silent Install option

### ISSUE THREAD

**Issue by binarylandscapes** [yuk7/wsldl#20]
I am trying to add an Alpine distro that uses your exe to my deployment and the final installation step where it asks to for user input to continue is a manual steps I would like a flag to install silently. Is this possible?

**Comment by yuk7** [comment]
Thank you for your suggestion.
Ok,I'll work for it.

Sorry for my late reply...

**Comment by yuk7** [comment]
I created silent install option on 159cf0d6d12d540885ac818029104c5c5e973579.
Please use this command:
```
Launcher.exe silent
```
