### ISSUE TITLE
how to use backup command?

### ISSUE THREAD

**Issue by mealayaria** [yuk7/wsldl#34]
when I use backup command I got this error:
![image](https://user-images.githubusercontent.com/4319965/53890871-09648280-4064-11e9-8c18-c3e5e9d2d0fe.png)

So what is the correct way to use backup command?

**Comment by yuk7** [comment]
I think it is a bug.
I have not confirmed the behavior with zsh...

**Comment by yuk7** [comment]
There seems to be no problem with your usage.
I think it is a bug.

The backup command saves backup.tar.gz in the current directory.

**Comment by yuk7** [comment]
fixed.

backup command can output backup.tar.gz to the current directory.
