### ISSUE TITLE
Rootfs for debian?

### ISSUE THREAD

**Issue by JbalTero** [yuk7/wsldl#37]
When using debian stretch rootfs, I always get this error: 

```
Installing...
ERROR:Installation Failed!
HRESULT:0x80004005
Press any key to continue...
```

**Comment by yuk7** [comment]
Is kind of file is that?
What command did you use to create it?

**Comment by JbalTero** [comment]
I downloaded the rootfs from here: https://github.com/DDoSolitary/LxRunOffline/wiki

using this link: https://lxrunoffline.apphb.com/download/debian/stretch

**Comment by benzBrake** [comment]
you should convert rootfs.tar.xz to rootfs.tar.gz
