### ISSUE TITLE
WSL2 support?

### ISSUE THREAD

**Issue by oscarbg** [yuk7/wsldl#42]
i.e. can we convert successfully to WSL 2 ?( via: wsl --set-version Distro 2)

**Comment by yuk7** [comment]
Yes,probably.

**Comment by oscarbg** [comment]
sadly I tried and had no luck with Clear Linux WSL project which uses wsldl internally seems..
details here:
https://github.com/wight554/ClearWSL/issues/2

**Comment by bentterp** [comment]
I've done with the CentOS release, and back again
