### ISSUE TITLE
After unregistering a wsldl distro, I can no longer install any - HRESULT:0x80070001

### ISSUE THREAD

**Issue by iCodeSometime** [yuk7/wsldl#43]
I followed the following process, and as a result of it am no longer able to install any wsldl distro.

1. Installed ArchLinux using the zip package.
2. A few days later, I uninstalled by `wsl --unregister Arch` (I guess this is what caused the problem? I now know, I should have run `Arch.exe clean` instead)

After following these steps, I tried running Arch.exe without changing anything (rootfs untouched, etc), but I get the error `ERROR:Installation Failed! HRESULT:0x80070001`
I also tried re-downloading and unzipping, but get the same error.
I also tried installing Artix, but get the same error.

If I install ubuntu from the microsoft store it works properly.

**Comment by iCodeSometime** [comment]
Additional info:
If I run `Arch.exe clean` now, it states that Arch is not installed.
If I run `wsl -l`, Ubuntu is the only distro listed.

If I decompress the rootfs and use `wsl --import Arch L:\Arch L:\Arch\rootfs.tar` I get an incorrect function error (not sure this should work)

**Comment by yuk7** [comment]
WSL instances can only be installed on C: drive.

**Comment by iCodeSometime** [comment]
Thank you. After moving the folder to `C:\` I get the same error when I launch Arch.exe, but `wsl --import` works properly.

The distro works correctly after running the import through wsl.

**Comment by iCodeSometime** [comment]
It looks like this issue only affects the distro that was unregistered, but it does also happen using the clean function of the exe.

e.g. I can reproduce this through.
```./Arch.exe # installs
./Arch.exe clean #uninstalls
./Arch.exe # gives error
wsl register 
```

I can not get around this by changing the exe name, but can by using a different distribution.
e.g. Artix will install while Arch is broken, but renaming Arch to Arch2.exe does not work.

**Comment by iCodeSometime** [comment]
Turns out the second error I got was because I had only the unzipped version of the tar file in the directory any more.

Looks like the drive requirement was the main issue here.
Thanks again for the help
