### ISSUE TITLE
run subcommand requires bash

### ISSUE THREAD

**Issue by aquaherd** [yuk7/wsldl#44]
A very small alpine linux install should also work without bash to fork a run command argument.
Ideas:
- make also default shell a configuration item: e.g. /bin/ash instead of /bin/bash
- rework forking in run command to use the default shell
- check if upstream API error

Reproduction:
- Install alpine WSL
- apk add bash
- alpine.exe run ps (works)
- apk del bash
- alpine.exe run ps (fails)
- alpine.exe run /bin/sh -c '/bin/ps' (fails)

**Comment by yuk7** [comment]
wsl specification.
There is nothing I can do.
