### ISSUE TITLE
Oracle Linux 8

### ISSUE THREAD

**Issue by yanko** [yuk7/wsldl#45]
is there a way to load oracle linux with wsldl?

**Comment by yuk7** [comment]
Please create rootfs.tar.gz

**Comment by yuk7** [comment]
Please create rootfs.tar.gz

**Comment by yuk7** [comment]
Please create rootfs.tar.gz and put on same directory and Double click exe

**Comment by yanko** [comment]
since I am new to this, where would you create the file from? docker? any links I can follow?

thank you.

**Comment by yuk7** [comment]
You can create image from docker or qcow2,etc.

If you create image file from Docker,Do this in root user on Linux machine:
1. Get base image from docker
Please get base .tar file with `docker save` or `docker export` command.

2. Extract base image file
Please extract base.tar image
```
mkdir root;cd root
tar -xvf ../base.tar
```

3. Settings for WSL
Setting for DNS resolver in WSL
```
echo "# This file was automatically generated by WSL. To stop automatic generation of this file, remove this line." > etc/resolv.conf
```

4. Compress rootfs.tar.gz
```
tar -zcpf ../rootfs.tar.gz *
```

**Comment by yuk7** [comment]
You can't use docker export image as-is.
Recompression is required due to docker export file structure.

**Comment by yanko** [comment]
will try it, hopefully later today.
thank you.

**Comment by yuk7** [comment]
Ok
If you have any question,please ask to me
