### ISSUE TITLE
Is it possible to install Funtoo, Gentoo and Solus with this repo?

### ISSUE THREAD

**Issue by gusbemacbe** [yuk7/wsldl#46]
Hello,

I wonder if I can install them with your repo.

**Comment by yuk7** [comment]
I don't provide those packages.
But you can create rootfs.tar.gz yourself.

**Comment by gusbemacbe** [comment]
> But you can create rootfs.tar.gz yourself.

To download an ISO or a tar.gz from the official site and to rename it to rootfs.tar.gz?

**Comment by yuk7** [comment]
No.
Probably You must re-compress tarball.
And if you use network,you can configure resolv.conf for WSL.

**Comment by gusbemacbe** [comment]
Hello @yuk7!

Following your suggestions. Only Funtoo and Gentoo worked. Solus did not work. 

Solus did not work because I received the warning «`FATAL: kernel too old`». If you want to know how I imported Solus as a distribution for WSL. Here is:

1. I downloaded an ISO from the official site of Solus;
2. I mounted the ISO;
3. I mounted the `squashfs.img` with `losetup -f -P`;
4. I mounted the `rootfs.img` with `losetup  -f -P`;
5. I copied everything from the img, using the command `sudo rsync -avzP /run/media/rootfs ~/rootfs`;
6. I entered the folder `rootfs` and compressed as `rootfs.tar`, running the command `sudo tar -cvphf solus.tar *`. 
7.  On Windows Terminal, I ran `wsl --import Funtoo C:\Users\gusbe\Applications\WSL\Solus C:\Users\gusbe\Downloads\Distro-Installers\solus.tar -- version 2`.

**Comment by yuk7** [comment]
It seems that glibc target linux kernel version too old.
Please rebuild glibc.

**Comment by gusbemacbe** [comment]
> Please rebuild glibc.

It is impossible to rebuild inside the Solus distro. If you run `eopkg glibc`, it will return the same error.

**Comment by yuk7** [comment]
Please do in Linux machine.
You must specified Linux kernel version for building glibc

**Comment by gusbemacbe** [comment]
> Please do in Linux machine.
> You must specified Linux kernel version for building glibc

After convert .vdi to .img, and .img to rootfs.tar.gz ore rootfs.tar or solus.tar (I run to import with wsl)?

**Comment by yuk7** [comment]
before packing solus.tar

**Comment by gusbemacbe** [comment]
> before packing solus.tar

I am a bit confused.

Do you mean .vdi to .img to solus.tar and import the solus.tar with the command `wsl` in the terminal?

**Comment by yuk7** [comment]
glibc is a important library used from all.
Therefore, you need to include the available GLIBC in the package before installing it in the WSL.

**Comment by gusbemacbe** [comment]
Hi @yuk7 !

I upgraded the glibc and the Linux kernel version of Solus in the virtual machine the which I converted img, exported the img to rootfs.tar.gz, but unfortunately I still received the "FATAL: kernel too old".

**Comment by gusbemacbe** [comment]
@yuk7 

I exported the Solus image from Docker as `rootfs.tar.gz`, but unfortunately I receive the same error `FATAL: kernel too old`.

**Comment by yuk7** [comment]
My explanation was not good.
Please fix the Linux version to 4.4.0

**Comment by yuk7** [comment]
Oh,I have now realized that you are using WSL2.
Since WSL2 can replace the kernel,replace the WSL kernel with a new one.

If you used WSL1,you had to compile glibc for the old kernel.

**Comment by rescenic** [comment]
https://github.com/sileshn/SolusWSL 
need WSL2 or kernel too old.

**Comment by rescenic** [comment]
https://github.com/rescenic/FuntooWSL
Add general first setup.
Gentoo and Funtoo are best suited with WSL2 so you can upgrade the kernel.
