### ISSUE TITLE
Make the instance thumb drive portable

### ISSUE THREAD

**Issue by cautionbug** [yuk7/wsldl#47]
Probably an enhancement, but i'm not sure how difficult it would be. ~It's possible this belongs over in your [yuk7/wsldl](/yuk7/wsldl) project.~ 🤷‍♂ (intended to register this issue on the CentWSL project. Oops.)

i'd like to install this instance on a thumb drive so i can take it with the rest of my dev environment. i'm aware that when the thumb drive is plugged into another system, the new machine will need to register the WSL instance.

Right now when i attempt to install from the thumb drive, i see:
```
PS W:\env\wsl\CentWSL> .\CentOS.exe
Installing...
ERROR:Installation Failed!
HRESULT:0x80070057
Press any key to continue...
```
If i install on an internal drive and attempt to migrate it to the thumb, i start down a rabbit hole of registry changes and other things that ultimately don't work:
```
The parameter is incorrect.
```
No idea what originates it. Maybe a `debug` argument for the EXE could also be added? 😁 

If you decide to try this, let me know how i can contribute.

**Comment by cautionbug** [comment]
That makes sense, and for the machines i'm concerned about at the moment, they'll be on the same build. i format my thumb drives to NTFS, so that doesn't seem a concern either. But i realize these are specialized conditions, so wouldn't be a "general use" feature.

If you can offer some guidance which registry entries i need to look for and adjust, i'm comfortable making a REG export that i can put on the thumb drive to hack it onto other machines...

**Comment by yuk7** [comment]
WSL registory is under HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Lxss
I have confirmed that it is registered even if I manually manipulate the registry.

**Comment by cautionbug** [comment]
Excellent. Thanks for the help - again. i'll try it myself later on. Cheers.

**Comment by cautionbug** [comment]
Following up ... It's been a little while, but i finally got my WSL instance the way i wanted and did a backup.

i've copied the instance (everything in the directory with CentOS.exe) to my thumb drive, and changed the `BasePath` registry key where you indicated.

However, it still fails to launch from the thumb drive. i get a simple "`The parameter is incorrect.`" message with no other info. i can't find any clues in Event Viewer.

Any additional suggestions, or should i just expect to set up separate WSL instances on each computer? Thanks for your assistance. :)

**Comment by yuk7** [comment]
I tried copy all NTFS tags,but I got "Access Denied".
It seems that external storage cannot be used,but you can install using a virtual HDD (VHDX).

When using virtual HDD and registry editing, it was confirmed that other computers can be used normally.

**Comment by cautionbug** [comment]
Thank you for investigating - i truly appreciate it.

i'll examine options for the VHDX that might help me move forward. Having a virtual drive emulator installed shouldn't be a big deal. Just one more step in environment setup. :)

**Comment by cautionbug** [comment]
Confirming that this approach works.

1. Create a VHDX on the portable drive with Windows Disk Manager
2. Attach and mount the VHDX
3. Drop CentWSL on the mounted drive and install it.

Excellent! i didn't even need to edit the registry, as long as i cleared my original CentWSL installation.

Thank you for investigating - i truly appreciate it.

**Comment by yuk7** [comment]
Ok!
