### ISSUE TITLE
CentOS 6 problem running

### ISSUE THREAD

**Issue by chrisplusplus** [yuk7/wsldl#49]
Hi I have tried following the instructions using http://cloud.centos.org/centos/6/images/CentOS-6-x86_64-GenericCloud-1907.raw.tar.gz as the rootfs.   It installs properly but when I try to run the executable it simply doesn't work.  It seems that the program just exits without any output.  Any ideas?

**Comment by yuk7** [comment]
Please convert the file.
That file is raw.tar.gz,it is raw disk image file.
The file system must be directly in tar.gz.

**Comment by yuk7** [comment]
https://github.com/yuk7/CentWSL/issues/24

I have confirmed the problem. I think this is a WSL issue...

**Comment by chrisplusplus** [comment]
Any chance this is a minimum version kernel issue?  Im not really sure just
asking

**Comment by am11** [comment]
Same issue with the native `wsl.exe --import` switch. It just exists with code 1. I couldn't find any useful/readable error message from logs, so reported the issue upstream: https://github.com/microsoft/WSL/issues/4749.

**Comment by yuk7** [comment]
Ok,This should be discussed [there](https://github.com/microsoft/WSL/issues/4749) in the future.

https://github.com/microsoft/WSL/issues/4749
