### ISSUE TITLE
add support to change dir when lanuch exe

### ISSUE THREAD

**Issue by jenningsloy318** [yuk7/wsldl#50]
Hi,

Can we support to add arg to the comman that change the dir inside of wsl, that is when excute the command line with the dir argument, we can chane to the coresponding directory specified.

for example, excute `Centos.exc -p /tmp `, and then we are in `root@hostname:/tmp `

**Comment by yuk7** [comment]
hmm.
Currently, it can be achieved with `centos.exe run "cd /tmp; bash"`.

**Comment by jenningsloy318** [comment]
worked, thanks so much.
