### ISSUE TITLE
silent option no longer works

### ISSUE THREAD

**Issue by binarylandscapes** [yuk7/wsldl#51]
What you added in this closed issue, no longer works https://github.com/yuk7/wsldl/issues/20

**Comment by yuk7** [comment]
Sorry,the silent option has been removed.
Please use install option

https://github.com/yuk7/wsldl/wiki/Hidden-Commands#install-option-silent

**Comment by binarylandscapes** [comment]
Got it. Feel free to close. Apologies for me not digging deeper first

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lucasvc** [comment]
Is there any flag to force/silent install of local `ext4.vhdx`, like it is done with `rootfs.tar.gz`?
I've tried with (following hidden options),
```
{InstanceName}.exe install ext4.vhdx
```
but no output shown and not instance registration is done either.

I've came with (after reading #106),
```
echo y | {InstanceName}.exe >nul
```
which seems a little bit tricky.

**Comment by yuk7** [comment]
@lucasvc 
What is your launcher version?
Direct installation of vhdx has recently been added to support.
You can check it with this command:
 ```Arch.exe version```

**Comment by yuk7** [comment]
@lucasvc
If you follow the launcher installation process, you can rename `ext4.vhdx` to `install.ext4.vhdx` and use it.
```
move ext4.vhdx install.ext4.vhdx
{InstanceName.exe} install
```

The ability to re-register from ext4.vhdx in the directory is beta, so there is no command line option yet.

**Comment by lucasvc** [comment]
With the `install` filename worked like a charm 😀
