### ISSUE TITLE
Connect to existing rootfs

### ISSUE THREAD

**Issue by HanabishiRecca** [yuk7/wsldl#54]
After Windows reinstallation WSL records obviously lost. And you can't just run Arch.exe with your existing rootfs folder and continue to work.
I've found a workaround: rename old rootfs, install new distro from rootfs.tar (just to register it), then delete and return old rootfs.
But this is inconvinient, why not just to connect to existing rootfs folder if it already exists?

**Comment by yuk7** [comment]
Added the backup function of the setting registry in the latest version of wsldl.
It is not a function to connect to an existing rootfs, but it can help you restore your configuration.

**Comment by HanabishiRecca** [comment]
Nice! Such fast response. Actually this solution does the trick. Even if distro was moved you can just modify the path inside the reg file. So thanks.

**Comment by yuk7** [comment]
Although only WSL1, wsldl/ArchWSL has a function to automatically correct the path when an instance moves. Please remember if you like!
