### ISSUE TITLE
[Suggestion] Select default terminal

### ISSUE THREAD

**Issue by HanabishiRecca** [yuk7/wsldl#58]
For example to startup in **Windows Terminal** instead of default cmd conhost.
![изображение](https://user-images.githubusercontent.com/13597663/75537674-44ac4e00-5a39-11ea-8dcc-8cf20c98bcfe.png)
Is this possible?

**Comment by HanabishiRecca** [comment]
I've analyzed WT again and now starting to realize this is not possible 🤔

**Comment by yuk7** [comment]
I think too it is difficult...
Please let me know if there is any good way.

**Comment by yuk7** [comment]
I'll work for this.

**Comment by yuk7** [comment]
Added terminal selector in latest release.
https://github.com/yuk7/wsldl/releases/latest

`Arch.exe config --default-terminal wt` for set default terminal to "Windows Terminal".

**Comment by HanabishiRecca** [comment]
Wow. You're the best dev I've ever met 👍
