### ISSUE TITLE
ERROR:Installation Failed!

### ISSUE THREAD

**Issue by fluffyloopy** [yuk7/wsldl#60]
![image](https://user-images.githubusercontent.com/36381994/77449886-599bb780-6e14-11ea-8cef-d2f2cdd17668.png)

**Comment by yuk7** [comment]
What did you do?
And please tell me your environment:
 - Windows build number: [e.g. 10.0.17134.228] (Type `ver` at a Command Prompt)
 - Security Software: [e.g. ESET Internet Security]
 - Launcher version [e.g. 19030700] (Type `Void.exe version` at a Command Prompt)

**Comment by fluffyloopy** [comment]
i just opened it. on my desktop.

![image](https://user-images.githubusercontent.com/36381994/77482056-e2cbe200-6e46-11ea-83d0-8139cc9df607.png)
![image](https://user-images.githubusercontent.com/36381994/77482090-f119fe00-6e46-11ea-8a23-a08321470f4b.png)

cant recreate it tho. it gives this now after pc restart 
![image](https://user-images.githubusercontent.com/36381994/77482576-0e030100-6e48-11ea-9883-bd178f95598a.png)

**Comment by fluffyloopy** [comment]
![image](https://user-images.githubusercontent.com/36381994/77483533-2f64ec80-6e4a-11ea-8302-f4697dfe508c.png)
when i used arch's rootfs i downloaded from their website

**Comment by yuk7** [comment]
Those error codes look different.
Arch rootfs needs to be converted.
https://git.io/archwsl

**Comment by fluffyloopy** [comment]
How bout void? No idea?

**Comment by yuk7** [comment]
The second error appears to have a problem with the installation.
Please run this on administrator cmd and retry it?
```
wslconfig /r Void
sc stop LxssManager
sc start LxssManager
```
Delete temp and rootfs folder.(Not .tar.gz)
retry

**Comment by fluffyloopy** [comment]
![image](https://user-images.githubusercontent.com/36381994/77526897-21948300-6ead-11ea-88c8-48a3efe83548.png)
![image](https://user-images.githubusercontent.com/36381994/77526926-2bb68180-6ead-11ea-9acc-e2da7e71aa07.png)

**Comment by yuk7** [comment]
I'm sorry,I'm mistake.
wslconfig command is:
```
wslconfig /u void
```

**Comment by fluffyloopy** [comment]
same errors

**Comment by yuk7** [comment]
0x8007002?
Is the installation completed?

**Comment by fluffyloopy** [comment]
yes, that happens after the installation completes

**Comment by yuk7** [comment]
Would you like to see if this works?
https://github.com/yuk7/AlpineWSL/releases/tag/19010200

If this work, you probably have a problem with that void image.

**Comment by fluffyloopy** [comment]
yes alpine works perfectly. but what do i do about void then?
