### ISSUE TITLE
does wsldl supposed with wsl2？

### ISSUE THREAD

**Issue by cyber-pixel** [yuk7/wsldl#61]
there is a problom when i use pycharm  【At the moment PyCharm supports WSL installations only from Microsoft Store.】https://youtrack.jetbrains.com/issue/PY-32424，so this repo is useful when wsl ，what about wsl2？

**Comment by yuk7** [comment]
Could you try this?:
https://www.jetbrains.com/help/ruby/configuring-remote-interpreters-using-wsl.html#custom_wsl
