### ISSUE TITLE
PhpStorm and custom WSL

### ISSUE THREAD

**Issue by Geelik** [yuk7/wsldl#73]
So i finally found a way to make phpstorm recognise imported WSL distribution (thanks to your tool).

I am on Windows 10
PhpStorm 2020.2.3 (using toolbox)

Steps to reproduce

1. Follow the installation instructions **BUT** rename the launcher  the same as one of this
```
// Found in AppData\Roaming\JetBrains\PhpStorm2020.2\options\wsl.distributions.xml
debian.exe
kali.exe
opensuse-42.exe
sles-12.exe
sles-15.exe
openSUSE-Leap-15.exe
ubuntu.exe
ubuntu1604.exe
ubuntu1804.exe
wlinux.exe
pengwin.exe
wle.exe
Arch.exe
openSUSE-Leap-15-1.exe
```
The reason for this is, all the paths for WSL executables are hard coded so even if you add a custom distribution in `wsl.distributions.xml` it will not work.

**The name of the executable is not obligatory the same as the ditribution it run !**
You can install Ubuntu with a launcher named `debian.exe` and it will work.

2. Move the executable in `C:\Users\USER\AppData\Local\Microsoft\WindowsApps`
3. Open or reopen Phpstorm and if all is good you can use WSL as an interpreter for PHP and nodejs

I would like people to confirm if it's working for them and maybe add it to the readme.

**Comment by yuk7** [comment]
I have set up a new repository for wiki and documentation and decided to link from the README.
https://github.com/wsldl-pg/docs/wiki/With-Other-Software

I want you to help me edit it.
Can I invite you to the team?

**Comment by yuk7** [comment]
But... `wsl.distributions.xml` really doesn't work??
https://github.com/JetBrains/intellij-community/blob/74c1c18870e3e16acfb78308b4f5052ec6246754/platform/platform-impl/src/com/intellij/execution/wsl/WSLDistributionService.java
I read the source code and it looks like `wsl.distributions.xml` is loaded.

**Comment by Geelik** [comment]
The source you provided is for intellij-community, i don't know if phpstorm use exactly the same base. And i tried everything with `wsl.distributions.xml` and nothing worked that's why it would be helpfull to have feedback from other users.

As for the documentation i don't have much free time so i'll not be very active but i can help from time to time if needed.

**Comment by yuk7** [comment]
Thank you so much!
I invited to organization.

**Comment by yuk7** [comment]
Can you create document about this to `PHPStorm.md` in [wsldl-pg/docs/Other-Software](https://github.com/wsldl-pg/docs/new/main/Other-Software/) ?
Thank you.

**Comment by Geelik** [comment]
Will try to do it tomorrow
