### ISSUE TITLE
how about reset command?

### ISSUE THREAD

**Issue by Schokokex** [yuk7/wsldl#77]
what do you think about a reset command (clean+install)? rootfs.tar.gz has to be in the same directory then.

**Comment by yuk7** [comment]
I think that's a good idea.
Do you often reset your instance?

**Comment by Schokokex** [comment]
yes, i try different Desktop Environments and have to reset if it does not work
its basically delete and create again

**Comment by Schokokex** [comment]
made a pull request. maybe do a quick test

**Comment by yuk7** [comment]
Merged
