### ISSUE TITLE
Test on ARM failed

### ISSUE THREAD

**Issue by lpwisniewski** [yuk7/wsldl#80]
I'm currently using a Surface Pro X and tried your arm build.
It fails like this:

```Using: C:\Users\lolow\Downloads\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x8007019e
Press any key to continue..
```
Don't hesitate to ask if you need any help or test on my side ! Thank for your work :D

**Comment by yuk7** [comment]
Wow! Thats amazing!
Thank you!

But, I think the error code is when the WSL function is not enabled.  Please check again.

**Comment by lpwisniewski** [comment]
Ahaha, I feel really dumb. I'll test again and let you know :D

**Comment by yuk7** [comment]
I tested works on ARM64
