### ISSUE TITLE
How do I restore from the backup?

### ISSUE THREAD

**Issue by flickerfly** [yuk7/wsldl#83]
I have run the backup of reg and tar. How do I restore this?

**Comment by yuk7** [comment]
Thanks for your questions.
There are two ways:
1. Rename the file to rootfs.tar and run the exe
2. Execute the `{InstanceName} .exe install backup.tar` command

**Comment by flickerfly** [comment]
Thanks! 

For others coming behind. I used method 2. 

I had to do this to prep because I had been messing around already.
`{InstanceName}.exe clean `

Also, I opened the Registry Editor and poked around.
Since I used method 2 instead of method 1, importing the registry file didn't seem to be needed. I just had to issues this to restore my command.
`{InstanceName}.exe --default-uid 1000 `
