### ISSUE TITLE
Installation "with any rootfs" impossible on arm laptops without virtualization

### ISSUE THREAD

**Issue by KritantaDev** [yuk7/wsldl#92]
Snapdragon 550 chips (and others, i'm sure) aren't likely going to see the same virtualization support that new chips have unless someone else writes the drivers. Windows itself also doesn't support this. 

I wouldn't say you *need* to support this, but it's taken me about a week to figure out manually, and others on pre 800/c snapdragon chips may also appreciate it.

Error: (virtualization isn't enabled, ofc)

```
PS C:\Users\krita\Downloads> .\Launcher_arm64.exe
Using: C:\Users\krita\Downloads\rootfs.tar.gz
Installing...
ERROR:Installation Failed!
HRESULT:0x80370102
```

I was able to circumvent this by manually importing the rootfs in WSL and working out how to get wsldl working with that.

dl: https://cloud-images.ubuntu.com/groovy/current/groovy-server-cloudimg-arm64-wsl.rootfs.tar.gz
`wsl --import Ubuntu2010 C:\Users\krita\Ubuntu .\rootfs.tar.gz --version 1`

an option or envar to force WSL version 1 (before install) or automate the above process in some way would be neat.

**Comment by yuk7** [comment]
Thank you for reporting issue
I'll investigate about it

**Comment by KritantaDev** [comment]
It's worth noting wsl.exe itself has this same issue, so I don't know if it's a bug as much as a feature request.

Let me know if you need any testing done.

**Comment by yuk7** [comment]
I checked on ARM64 and no virtualization, but it works.
