### ISSUE TITLE
Improve description of the project [-Documentation-]

### ISSUE THREAD

**Issue by minhaj6** [yuk7/wsldl#94]
Hey yuk7 and contributors! 

`"Advanced WSL Distribution Launcher / Installer"` in the github readme page or `"wsldl is a versatile WSL launcher / installer."` in the Detailed documentation page is not enough to describe what the software does ( in my case at least ).

You have listed some projects that are using this software, how to use, command line usage etc., and they are amazing documentation work. But I think, an "about" page or a little bit more elaborate description is much needed. By elaborate I mean, a 5-10 lines long description of that the software actually does will help a ton. 

I feel the need to say this because I can not seem to find out what this software actually is and if I need it or not. I have searched the internet but failed to find writings/videos featuring this project. I am sure that it won't be a problem for people in the WSL community, but adding this description would help us, outsiders to get to know your software. 

Well Wishes, you guys are doing amazing job!

**Comment by locobastos** [comment]
Hello Minhaj,

Thank you for this issue.

If someone does not know what WSL is, he won't understand what WSLDL is.
If yuk7 quote the little description from the official Microsoft website (https://docs.microsoft.com/en-us/windows/wsl/about)

    The Windows Subsystem for Linux lets developers run a GNU/Linux environment -- including most command-line tools, utilities, and applications -- directly on Windows, unmodified, without the overhead of a traditional virtual machine or dualboot setup.

Will it be enough for you ?

**Comment by minhaj6** [comment]
Hey! thank you for your kind response.
 
See, there is a little gap, at least for me. I am pretty sure that there are a lot of people like me.  Consider this, 
1. I read somewhere that there is something called WSL and WSL2 that allows running GNU Linux in windows 10. I am happy.
2. I **enable the windows feature**, download WSL2 kernel. 
3. Install a distro from **Microsoft Store** and installed a terminal emulator (Windows Terminal).
4. Only few distros are available in Microsoft Store. I am more familiar with a different distribution (Archlinux). 
---
5. Searching for it, I found that there exist a **Launcher** based on which there are several github projects. (unofficial gnu/linux wsl distros like archlinux and some more).
6. I am curious, interested and trying to figure out how is this happening. The only way I *launched* wsl distros before was through a terminal emulator, in some form or other, as far as I'm concerned. But now there is a **Launcher** that can install other distributions!! I am very fascinated by this magic.
7. I want to learn at least at a higher level, what's happening. I search everywhere about this WSLDL magic but can't find any article or anything that describes the work of WSLDL. 
8. I open a GitHub issue requesting a higher level description of their project because I am really interested to know,.
