### ISSUE TITLE
ERROR:[2] Could not read registry key

### ISSUE THREAD

**Issue by workdowg** [yuk7/wsldl#98]
Microsoft Windows [Version 10.0.22000.51]
WSL2
Fresh install using the APPX

I get this error on the command each time I open the window. It happens regardless of how I launch it (Windows Terminal, Powershell or the Start Menu launcher). Nothing else seems to be affected but I would like this to not happen. A fresh Ubuntu install does not get this error.

Thanks.

**Comment by locobastos** [comment]
You are not supposed to have many different WSL on your system.
I had this error message when I had more than 15 differents WSL.
What I've done to resolve it, was to clean all useless WSL then clean my registery.
I'm not available right now, I'll try later to help you better.

**Comment by yuk7** [comment]
Oh, Thank you for your information.

**Comment by workdowg** [comment]
Thanks for being on top of this! 
This is a fresh Windows and I only installed Ubuntu to see if it had the same issue.

**Comment by MadCabbit** [comment]
I just did a reset on Windows 11 Insider Build 22000.51.  I did the new "wsl -- install" command that works on insider builds to install wsl 2 and it's components and installs Ubuntu by default.  I'm getting the same error when launching Arch after installing  the APPX.

**Comment by workdowg** [comment]
I put this issue under the wrong git page. Should be under ArchWSL. My fresh install was actually the Windows 11 preview also... I didn't notice it installs Ubuntu first...

**Comment by yuk7** [comment]
I'm also using Windows 11 Insider preview,but I haven't encountered any issues like this...
It may be due to the security mechanism of appx.

**Comment by locobastos** [comment]
So, here is what I've done to fix the error when I encountered it:
(sorry, I did that many months ago and I've not took notes)

1. Probably a `wsl --shutdown`
2. `my-wsl.exe clean` for each useless WSL instances
2. regedit > `HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Lxss`
3. Delete remaining "{UUID}" folders related to my previous deleted WSL instances.
4. Maybe a reboot of my computer
5. Re-create my usefull WSL instance.

Note that I'm only use CentOS 7 (WSL).

Hope this will help you a little bit @yuk7 
Cheers

**Comment by locobastos** [comment]
@workdowg, Don't worry, you opened the issue on the ArchWSL GitHub Issues Page but @yuk7 moved it here.
Nothing to do on your side ;)

**Comment by 7k5x** [comment]
An APPX installation would be installed on `C:\Program Files\WindowsApps`, same as other UWP apps installed from the Microsoft Store, such as Ubuntu.
A high possibility for this issue is that you installed the certificate somewhere else other than the trusted certification authorities. Consider reinstalling the certificate as shown on [here](https://wsldl-pg.github.io/ArchW-docs/Install-Certificate/).
If that isn't the problem, then it could be a bug of privileges of windows.

**Comment by workdowg** [comment]
I removed Arch and reinstalled following the certificate instructions to the letter and same error. Guess we chalk it up to Windows 11....

**Comment by yuk7** [comment]
I'm working on fixing this issue now.
I think I'll release new version within a month.

**Comment by workdowg** [comment]
Ok! Take your time. You have done a great thing here.

**Comment by yuk7** [comment]
I fixed in new release!
